#!/bin/sh
set -u

subcommand=${1:-}
[ -n "$subcommand" ] || exit 127
shift

case "$subcommand" in
  flock)
    printf 'busybox flock %s\n' "$*" >> "$MOCK_CALL_LOG"
    exec "$MOCK_HOST_FLOCK" "$@"
    ;;
  wget)
    MOCK_TOOL_LABEL=busybox
    export MOCK_TOOL_LABEL
    exec "$MOCK_HOST_SH" "$MOCK_DOWNLOAD_HELPER" "$@"
    ;;
  sha256sum)
    [ "$#" -eq 1 ] || exit 64
    printf '%s  %s\n' "$MOCK_ACTUAL_SHA" "$1"
    ;;
  *)
    exit 127
    ;;
esac
