#!/bin/sh
set -u

destination=
while [ "$#" -gt 0 ]; do
  case "$1" in
    -d)
      shift
      [ "$#" -gt 0 ] || exit 64
      destination=$1
      ;;
  esac
  shift
done

[ -n "$destination" ] || exit 64
printf 'unzip\n' >> "$MOCK_CALL_LOG"

case "$MOCK_UNZIP_MODE" in
  success)
    mkdir -p "$destination/$MOCK_INNER_DIR"
    printf '%s\n' \
      '#!/bin/sh' \
      '# mock dnscrypt binary' \
      'case "${1:-}" in' \
      '  -version) printf "%s\\n" "${MOCK_BINARY_VERSION:-$MOCK_LATEST_VERSION}" ;;' \
      '  -check) [ "${MOCK_BINARY_MODE:-success}" != "config-fail" ] ;;' \
      '  *) exit 64 ;;' \
      'esac' > "$destination/$MOCK_INNER_DIR/dnscrypt-proxy"
    ;;
  empty)
    mkdir -p "$destination/$MOCK_INNER_DIR"
    : > "$destination/$MOCK_INNER_DIR/dnscrypt-proxy"
    ;;
  missing)
    :
    ;;
  fail)
    exit 1
    ;;
  *)
    exit 64
    ;;
esac
